"""add milestone fields

Revision ID: 2633e65a6bde
Revises: 68e7ed1277d0
Create Date: 2025-05-05 10:45:27.842017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2633e65a6bde'
down_revision: Union[str, None] = '68e7ed1277d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.alter_column('milestone', 'category',
               existing_type=postgresql.ENUM('MOTOR', 'COGNITIVE', 'LANGUAGE', 'SOCIAL', 'EMOTIONAL', 'SELF_CARE', name='milestonecategory'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('milestone', 'achieved_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('milestone', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('milestone', 'is_achieved')
    op.drop_column('milestone', 'typical_age_months')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('typical_age_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('is_achieved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('milestone', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('milestone', 'achieved_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('milestone', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MOTOR', 'COGNITIVE', 'LANGUAGE', 'SOCIAL', 'EMOTIONAL', 'SELF_CARE', name='milestonecategory'),
               existing_nullable=False)
    op.drop_column('milestone', 'photo_url')
    # ### end Alembic commands ###
