"""add dashboard models

Revision ID: 29a0674c79b4
Revises: 53e845c69d6e
Create Date: 2025-05-12 07:16:15.831798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a0674c79b4'
down_revision: Union[str, None] = '53e845c69d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('layout_type', sa.String(length=50), nullable=False),
    sa.Column('default_baby_id', sa.Integer(), nullable=True),
    sa.Column('default_timeframe', sa.String(length=20), nullable=False),
    sa.Column('widgets_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['default_baby_id'], ['baby.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_preferences')
    # ### end Alembic commands ###
