"""add pumping_user relationship_fields

Revision ID: 2dad77df7cd0
Revises: 2633e65a6bde
Create Date: 2025-05-05 10:51:00.612147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dad77df7cd0'
down_revision: Union[str, None] = '2633e65a6bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pumping', sa.Column('left_amount', sa.Float(), nullable=True))
    op.add_column('pumping', sa.Column('right_amount', sa.Float(), nullable=True))
    op.add_column('pumping', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('pumping', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('pumping', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('pumping_baby_id_fkey', 'pumping', type_='foreignkey')
    op.create_foreign_key(None, 'pumping', 'users', ['user_id'], ['id'])
    op.drop_column('pumping', 'volume_right')
    op.drop_column('pumping', 'volume_left')
    op.drop_column('pumping', 'baby_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pumping', sa.Column('baby_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pumping', sa.Column('volume_left', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pumping', sa.Column('volume_right', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pumping', type_='foreignkey')
    op.create_foreign_key('pumping_baby_id_fkey', 'pumping', 'baby', ['baby_id'], ['id'])
    op.alter_column('pumping', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('pumping', 'user_id')
    op.drop_column('pumping', 'total_amount')
    op.drop_column('pumping', 'right_amount')
    op.drop_column('pumping', 'left_amount')
    # ### end Alembic commands ###
