"""add_recorded_by_to_feeding

Revision ID: 3e8a523dffc9
Revises: 29a0674c79b4
Create Date: 2025-05-13 07:11:17.474306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8a523dffc9'
down_revision: Union[str, None] = '29a0674c79b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeding', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feeding', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeding', type_='foreignkey')
    op.drop_column('feeding', 'recorded_by')
    # ### end Alembic commands ###
