""""Add recorded by to milestone"

Revision ID: 3e9c8d6cd26c
Revises: 8578603b15a4
Create Date: 2025-05-22 07:18:29.430291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9c8d6cd26c'
down_revision: Union[str, None] = '8578603b15a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('recorded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'milestone', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_column('milestone', 'recorded_by')
    # ### end Alembic commands ###
