"""roleback co-parent relationship_type

Revision ID: 53e845c69d6e
Revises: 2a8f100f05d5
Create Date: 2025-05-08 09:35:53.618681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e845c69d6e'
down_revision: Union[str, None] = '2a8f100f05d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('growth', sa.Column('percentile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth', 'percentile_data')
    # ### end Alembic commands ###
