"""add_recorded_by_to_diaper_nulls

Revision ID: 5717aa551aaf
Revises: 767dc24bd73a
Create Date: 2025-05-14 07:28:25.199733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5717aa551aaf'
down_revision: Union[str, None] = '767dc24bd73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaper', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diaper', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diaper', type_='foreignkey')
    op.drop_column('diaper', 'recorded_by')
    # ### end Alembic commands ###
