"""add medication fields

Revision ID: 68e7ed1277d0
Revises: 8d7beba0f458
Create Date: 2025-05-05 10:40:05.866489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e7ed1277d0'
down_revision: Union[str, None] = '8d7beba0f458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('dosage', sa.Float(), nullable=False))
    op.add_column('medication', sa.Column('dosage_unit', sa.String(length=20), nullable=False))
    op.add_column('medication', sa.Column('route', sa.String(length=20), nullable=False))
    op.add_column('medication', sa.Column('time_given', sa.DateTime(), nullable=False))
    op.add_column('medication', sa.Column('given_by', sa.String(length=100), nullable=True))
    op.add_column('medication', sa.Column('reason', sa.String(length=500), nullable=True))
    op.alter_column('medication', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('medication', 'reminders')
    op.drop_column('medication', 'active')
    op.drop_column('medication', 'dose')
    op.drop_column('medication', 'end_date')
    op.drop_column('medication', 'unit')
    op.drop_column('medication', 'time_of_day')
    op.drop_column('medication', 'frequency')
    op.drop_column('medication', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('medication', sa.Column('frequency', postgresql.ENUM('ONCE', 'DAILY', 'TWICE_DAILY', 'THREE_TIMES_DAILY', 'FOUR_TIMES_DAILY', 'WEEKLY', 'AS_NEEDED', name='medicationfrequency'), autoincrement=False, nullable=False))
    op.add_column('medication', sa.Column('time_of_day', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('dose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('reminders', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('medication', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('medication', 'reason')
    op.drop_column('medication', 'given_by')
    op.drop_column('medication', 'time_given')
    op.drop_column('medication', 'route')
    op.drop_column('medication', 'dosage_unit')
    op.drop_column('medication', 'dosage')
    # ### end Alembic commands ###
