"""add_recorded_by_to_diaper_not_nulls

Revision ID: 6cfa50e611c1
Revises: 5717aa551aaf
Create Date: 2025-05-14 07:30:39.866895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfa50e611c1'
down_revision: Union[str, None] = '5717aa551aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaper', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaper', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
