"""add_recorded_by_to_sleep_nulls

Revision ID: 6e61a5de49e4
Revises: d078273b07e5
Create Date: 2025-05-14 07:11:31.048739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e61a5de49e4'
down_revision: Union[str, None] = 'd078273b07e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sleep', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleep', type_='foreignkey')
    op.drop_column('sleep', 'recorded_by')
    # ### end Alembic commands ###
