"""add_recorded_by_to_health__nulls

Revision ID: 734556454946
Revises: 6cfa50e611c1
Create Date: 2025-05-15 07:34:05.266101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734556454946'
down_revision: Union[str, None] = '6cfa50e611c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'health', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health', type_='foreignkey')
    op.drop_column('health', 'recorded_by')
    # ### end Alembic commands ###
