"""add photo-milestone integration

Revision ID: 7dc3603ae280
Revises: d0683109de92
Create Date: 2025-05-05 15:14:39.886408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc3603ae280'
down_revision: Union[str, None] = 'd0683109de92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'milestone', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'milestone_id')
    # ### end Alembic commands ###
