""""add_recorded_by_to_growth"

Revision ID: 8578603b15a4
Revises: ef9df65b2d14
Create Date: 2025-05-21 07:13:55.266328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8578603b15a4'
down_revision: Union[str, None] = 'ef9df65b2d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('growth', sa.Column('recorded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'growth', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'growth', type_='foreignkey')
    op.drop_column('growth', 'recorded_by')
    # ### end Alembic commands ###
