""""Add recorded by to medication _non_Null"

Revision ID: 94e432490b69
Revises: a2a7991a327a
Create Date: 2025-05-20 07:34:06.049128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e432490b69'
down_revision: Union[str, None] = 'a2a7991a327a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medication', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('medication', 'given_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('given_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('medication', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
