""""Add recorded by to medication"

Revision ID: a2a7991a327a
Revises: c24c5d5721ed
Create Date: 2025-05-20 07:29:18.424143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a7991a327a'
down_revision: Union[str, None] = 'c24c5d5721ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medication', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.drop_column('medication', 'recorded_by')
    # ### end Alembic commands ###
