"""add doctor_visit fields

Revision ID: a8895afae02a
Revises: 94d3264819c9
Create Date: 2025-05-05 10:28:41.801593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8895afae02a'
down_revision: Union[str, None] = '94d3264819c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_visit', sa.Column('visit_type', sa.String(length=50), nullable=False))
    op.add_column('doctor_visit', sa.Column('diagnosis', sa.String(length=500), nullable=True))
    op.add_column('doctor_visit', sa.Column('treatment', sa.Text(), nullable=True))
    op.add_column('doctor_visit', sa.Column('next_appointment', sa.DateTime(), nullable=True))
    op.alter_column('doctor_visit', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('doctor_visit', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('doctor_visit', 'follow_up_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_visit', sa.Column('follow_up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('doctor_visit', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('doctor_visit', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('doctor_visit', 'next_appointment')
    op.drop_column('doctor_visit', 'treatment')
    op.drop_column('doctor_visit', 'diagnosis')
    op.drop_column('doctor_visit', 'visit_type')
    # ### end Alembic commands ###
