""""Add recorded by to photo"

Revision ID: b03329c3fda0
Revises: 3e9c8d6cd26c
Create Date: 2025-05-22 07:32:42.012247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03329c3fda0'
down_revision: Union[str, None] = '3e9c8d6cd26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('recorded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'photo', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'recorded_by')
    # ### end Alembic commands ###
