"""add_recorded_by_to_health_not_nulls

Revision ID: c24c5d5721ed
Revises: 734556454946
Create Date: 2025-05-15 07:45:16.044461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24c5d5721ed'
down_revision: Union[str, None] = '734556454946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
