"""add photo

Revision ID: d0683109de92
Revises: 67fa89f92d18
Create Date: 2025-05-05 14:24:03.019886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0683109de92'
down_revision: Union[str, None] = '67fa89f92d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('photo_type', sa.Enum('PROFILE', 'MILESTONE', 'GROWTH', 'OTHER', name='phototype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['baby.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
