"""add_recorded_by_to_feeding_not_nulls

Revision ID: d078273b07e5
Revises: 3e8a523dffc9
Create Date: 2025-05-13 07:38:32.520686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd078273b07e5'
down_revision: Union[str, None] = '3e8a523dffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feeding', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feeding', 'recorded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
