""""tool Fixed SQLEnum configuration"

Revision ID: e2a2acac98d6
Revises: 7e9cfdf6bbe4
Create Date: 2025-05-29 13:05:49.524088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a2acac98d6'
down_revision: Union[str, None] = '7e9cfdf6bbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool', 'tool_type',
               existing_type=postgresql.ENUM('activity_analyzer', 'sleep_pattern_analyzer', 'feeding_tracker', 'health_monitor', 'growth_tracker', 'milestone_tracker', 'care_metrics_analyzer', 'schedule_assistant', name='tooltype'),
               type_=sa.Enum('activity_analyzer', 'sleep_pattern_analyzer', 'feeding_tracker', 'health_monitor', 'growth_tracker', 'milestone_tracker', 'care_metrics_analyzer', 'schedule_assistant', name='tooltype', native_enum=False),
               existing_nullable=False)
    op.alter_column('tool', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'maintenance', name='toolstatus'),
               type_=sa.Enum('active', 'inactive', 'maintenance', name='toolstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool', 'status',
               existing_type=sa.Enum('active', 'inactive', 'maintenance', name='toolstatus', native_enum=False),
               type_=postgresql.ENUM('active', 'inactive', 'maintenance', name='toolstatus'),
               existing_nullable=False)
    op.alter_column('tool', 'tool_type',
               existing_type=sa.Enum('activity_analyzer', 'sleep_pattern_analyzer', 'feeding_tracker', 'health_monitor', 'growth_tracker', 'milestone_tracker', 'care_metrics_analyzer', 'schedule_assistant', name='tooltype', native_enum=False),
               type_=postgresql.ENUM('activity_analyzer', 'sleep_pattern_analyzer', 'feeding_tracker', 'health_monitor', 'growth_tracker', 'milestone_tracker', 'care_metrics_analyzer', 'schedule_assistant', name='tooltype'),
               existing_nullable=False)
    # ### end Alembic commands ###
