""""Add recorded by to doctor_visit"

Revision ID: ef9df65b2d14
Revises: 94e432490b69
Create Date: 2025-05-21 07:04:29.347126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9df65b2d14'
down_revision: Union[str, None] = '94e432490b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_visit', sa.Column('recorded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'doctor_visit', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_visit', type_='foreignkey')
    op.drop_column('doctor_visit', 'recorded_by')
    # ### end Alembic commands ###
