"""add growth percentile

Revision ID: f12573cff809
Revises: 98f310afb674
Create Date: 2025-05-06 09:23:12.876958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12573cff809'
down_revision: Union[str, None] = '98f310afb674'  # Updated to point to the correct previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('growth', sa.Column('percentile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth', 'percentile_data')
    # ### end Alembic commands ###